In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import math
import random
from sklearn.model_selection import KFold
df1 = pd.read_csv("HW1/train1.csv") 
df2 = pd.read_csv("HW1/train2.csv") 
df3 = pd.read_csv("train3.csv") #will be used in Part D

In [2]:
#By printing a dataframe, you can view the data in csv format
print(df1)

      Unnamed: 0        x1        x2    y
0              0  1.143987  0.339646  0.0
1              1  2.284493  1.129224  0.0
2              2  1.053601  0.573296  0.0
3              3 -0.652288  3.116746  1.0
4              4 -0.223255  3.463650  1.0
...          ...       ...       ...  ...
1595        1595 -1.415131  3.226519  1.0
1596        1596  1.645863  1.057249  0.0
1597        1597 -1.575476  3.638737  1.0
1598        1598  0.790778  0.626050  0.0
1599        1599 -0.292451  0.269355  0.0

[1600 rows x 4 columns]


In [3]:
#You can extract keys from dataframe, which you can use to extract features or labels.
print(df1.keys())
df1_x1 = df1['x1']
df1_x2 = df1['x2']
#To extract data as numpy array:
df1_numpy = df1.values
#You can also extract a specific feature as numpy array as well.
df1_x1_numpy = df1['x1'].values

Index(['Unnamed: 0', 'x1', 'x2', 'y'], dtype='object')


In [4]:
df1_data = df1.values[:,1:3]
df1_labels = df1.values[:, 3]
c1 = df1_data[df1_labels==0]
c2 = df1_data[df1_labels==1]
print(np.cov(c1.T))
print(np.cov(c2.T))

[[ 0.65160952 -0.01944138]
 [-0.01944138  0.36506496]]
[[0.41319973 0.01333729]
 [0.01333729 1.49504785]]


In [6]:
df2_data = df2.values[:,1:3]
df2_labels = df2.values[:, 3]
c3 = df2_data[df2_labels==0]
c4 = df2_data[df2_labels==1]
print(c3.shape, c4.shape)
cov1 =np.cov(c3.T)
cov2 = np.cov(c4.T)
print(cov1)
print(cov2)
print(cov1[0,0] - cov1[1,1])
print(cov2[0,0] - cov2[1,1])

print((cov1[0,0] - cov1[1,1]) < 1e-3)
print((cov2[0,0] - cov2[1,1]) < 1e-3)
print((cov1[1,0]) < 1e-3)
print((cov2[1,0]) < 1e-3)
print((cov1[0,1]) < 1e-3)
print((cov2[0,1]) < 1e-3)

(1000, 2) (1000, 2)
[[ 1.29952458e+00 -3.20601159e-05]
 [-3.20601159e-05  1.30047560e+00]]
[[ 8.99978203e-01 -1.96515212e-05]
 [-1.96515212e-05  9.00021797e-01]]
-0.0009510247003510219
-4.359403538800599e-05
True
True
True
True
True
True


# Add your comments as markdown cells(This is a markdown cell).

## To add a markdown cell, simply click on a cell, then click on the 'Cell' tab above, change 'Cell Type' to 'Markdown'

Then add your comment! To view the format of this markdown cell, double click on here.

### Note: We provide you with example codes for starter, but feel free to delete anything we provide and write your own code, as long as you use allowed libraries and modules. 

## Part A: Examine training sets

In [ ]:
#PART A: Examine training sets here. plots etc.
#Hint: df1_class0 = df1[df1['column_name']==0] creates a new dataframe and includes samples (rows) whose class values are 0
#hint: for data distribution plots use plt.scatter(x-axis,y-axis,other params. check online)
#Hint: for each new plot use plt.figure() so they won't overlap, one on top of another
#-------
#to plot cov. matrices you may use following code: (compute 'cov_mtrx' by yourself)
alpha = ['x1', 'x2']
fig = plt.figure()
ax = fig.add_subplot(111)
cax = ax.matshow(cov_mtrx,interpolation='nearest') #cov. matrix of dataset1
fig.colorbar(cax)
ax.set_xticklabels(['']+alpha)
ax.set_yticklabels(['']+alpha)
#---------
#for the histogram plots use plt.hist() (Remember: 4 of them we want)
#for title use: plt.gca().set(title='Data distribution of feature x of trainingSet y', ylabel='Frequency')

In [ ]:
#Implement PART B:
test1 = df.read_csv("test1.csv")
test2 = df.read_csv("test2.csv")

In [ ]:
#Implement PART C: